{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
stringData:
  POSTGRES_USER: {{ .Values.secrets.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.password | quote }}
  POSTGRES_DB: {{ .Values.secrets.database | quote }}
{{- end }}