{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }} # ClusterIP
  ports:
    - port: {{ .Values.service.port }} # 5432
      targetPort: {{ .Values.service.port }} # 5432
      protocol: TCP
  selector:
    app: {{ .Values.nameOverride }}
{{- end }}