enabled: true
nameOverride: inventory-service
image:
  repository: backend-inventory-service # ❗️ Имя
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 3004 # ❗️ Порт
  tcpPort: 4004  # ❗️ Порт
  targetHttpPort: 3004
  targetTcpPort: 4004

configMap:
  INVENTORY_SERVICE_HOST: "0.0.0.0"
  KAFKA_BROKER: "redpanda:9092"
  KAFKA_ENABLED: "true"
  REDIS_URL: "redis://redis:6379"
  REDIS_ENABLED: "true"
  ELASTICSEARCH_NODE: "http://elasticsearch:9200"
  ELASTICSEARCH_ENABLED: "true"
  CATALOG_SERVICE_URL: "http://catalog-service:3003/api"  
  CATALOG_SERVICE_HOST: "catalog-service"
  
secrets:
  JWT_ACCESS_SECRET: "default-access"
  JWT_REFRESH_SECRET: "default-refresh"
