enabled: true
nameOverride: search-service
image:
  repository: backend-search-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 3008
  tcpPort: 4009
  targetHttpPort: 3008
  targetTcpPort: 4009

configMap:
  SEARCH_SERVICE_HOST: "0.0.0.0"
  KAFKA_BROKER: "redpanda:9092"
  KAFKA_ENABLED: "true"
  REDIS_URL: "redis://redis:6379"
  REDIS_ENABLED: "true"
  ELASTICSEARCH_NODE: "http://elasticsearch:9200"
  ELASTICSEARCH_ENABLED: "true"
  CATALOG_SERVICE_URL: "http://catalog-service:3003/api"
  CATALOG_SERVICE_HOST: "catalog-service"
  USER_SERVICE_HOST: "user-service"
  
secrets:
  JWT_ACCESS_SECRET: "default-access"
  JWT_REFRESH_SECRET: "default-refresh"