{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-config
data:
  API_GATEWAY_PORT: {{ .Values.service.targetPort | quote }}

  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}