enabled: true

image:
  repository: backend-api-gateway 
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: api-gateway

service:
  type: NodePort
  port: 3000      
  targetPort: 3000 
  nodePort: 30000  
configMap:
  NODE_ENV: "production"
  API_GATEWAY_HOST: "0.0.0.0" 

  CATALOG_SERVICE_URL: "http://catalog-service:3003/api"
  AUTH_SERVICE_HOST: "auth-service"
  AUTH_SERVICE_HTTP_PORT: "3001"
  AUTH_SERVICE_PORT: "4001"
  USER_SERVICE_HOST: "user-service"
  USER_SERVICE_HTTP_PORT: "3005"
  USER_SERVICE_PORT: "4005"
  INVENTORY_SERVICE_HOST: "inventory-service"
  INVENTORY_SERVICE_HTTP_PORT: "3004"
  INVENTORY_SERVICE_PORT: "4004"
  MARKET_SERVICE_HOST: "market-service"
  MARKET_SERVICE_HTTP_PORT: "3006"
  MARKET_SERVICE_PORT: "4006"
  PAYMENT_SERVICE_HOST: "payment-service"
  PAYMENT_SERVICE_HTTP_PORT: "3002"
  PAYMENT_SERVICE_PORT: "4007"
  SEARCH_SERVICE_HOST: "search-service"
  SEARCH_SERVICE_HTTP_PORT: "3008"
  SEARCH_SERVICE_PORT: "4009"
  NOTIFICATION_SERVICE_HTTP_PORT: "3009"
  CATALOG_SERVICE_HOST: "catalog-service"
  CATALOG_SERVICE_HTTP_PORT: "3003"
  CATALOG_SERVICE_PORT: "4003"

  KAFKA_BROKER: "redpanda:9092"
  KAFKA_ENABLED: "true"
  REDIS_URL: "redis://redis:6379"
  REDIS_ENABLED: "true"
  ELASTICSEARCH_NODE: "http://es01:9200"
  ELASTICSEARCH_ENABLED: "true"

secrets:
  JWT_ACCESS_SECRET: "default-access"
  JWT_ACCESS_EXPIRATION: "15m"
  JWT_REFRESH_SECRET: "default-refresh"
  JWT_REFRESH_EXPIRATION: "7d"